# Generated by Django 5.2 on 2025-04-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcard_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.IntegerField(unique=True)),
                ('label', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
