# Generated by Django 5.2 on 2025-04-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_flashcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='flashcard_audio/'),
        ),
    ]
