# Generated by Django 5.2 on 2025-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_flashcard_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='card_audio/'),
        ),
    ]
